#!/bin/bash

# derived from here
# https://github.com/andrewseidl/githook-clang-format/blob/master/clang-format.hook
# Uses the _clang-format file for rules
# Uses the _clang-format_ignore file to skip dirs

format_file() {
  file="${1}"

  if [ -f $file ]; then
    clang-format -style=file -i ${file}
    git add ${file}
  fi
}

for file in `git diff-index --cached --name-only HEAD | grep -iE '\*.(cpp|h|m|mm)$' ` ; do
  format_file "${file}"
done

