name: "tagged-release"

# run on any changes tagged with v*, will copy data to releases
on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15, windows-2022]
        
    steps:
      - name: Update CMake
        uses: lukka/get-cmake@latest

      - name: Check out code
        uses: actions/checkout@v6

      - name: Build and install to bin/
        run: ./scripts/cibuild.sh ${{ matrix.os }}
        shell: bash

      - name: Upload all builds to releases
        uses: softprops/action-gh-release@v3
        with:
          prerelease: false # Forces GitHub to mark it as a Pre-Release
          draft: false
          generate_release_notes: true # Auto-generates changelogs using AI/commits
          files: bin/*.zip
